In [1]:
import pandas as pd
import numpy as np

In [2]:
file=pd.read_csv("mushrooms.csv")

In [3]:
file.head()

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   

  gill_spacing gill_size gill_color   ...   stalk_surface_below_ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

## into numerical data



In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [5]:
le=LabelEncoder()
file=file.apply(le.fit_transform)

In [6]:
file=file.values

In [7]:
print(file)

[[1 5 2 ... 2 3 5]
 [0 5 2 ... 3 2 1]
 [0 0 2 ... 3 2 3]
 ...
 [0 2 2 ... 0 1 2]
 [1 3 3 ... 7 4 2]
 [0 5 2 ... 4 1 2]]


In [8]:
m=int(0.8*file.shape[0])
x_train,y_train=file[:m,1:],file[:m,0]
x_test,y_test=file[m:,1:],file[m:,0]


In [9]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(6499, 22) (6499,)
(1625, 22) (1625,)


In [10]:
n=y_train.shape[0]

In [11]:
def prob_y(label,y_train,n):
    s=np.sum(y_train==label)
    return (s/n)

In [12]:
def classifier(y_train,x_test,x_train):
    p=np.unique(y_train)
    n=y_train.shape[0]
    m=x_train.shape[1]
    prob_y_x=np.zeros((len(p),))
    for i in p:
        prod=1
        for j in range(m):  
            x_fil=x_train[y_train==i]
            l=np.sum(x_fil[:,j]==x_test[j])
            prob=l/(x_fil.shape[0])
            prod*=prob
        prob_y_x[i]=prob_y(i,y_train,n)*prod
    index=prob_y_x.argmax()
    return p[index]

In [13]:
c=classifier(y_train,x_test[369],x_train)
print(c)
print(y_test[369])

1
1


In [14]:
def score(y_train,x_test,x_train):
    score=0
    for i in range(x_test.shape[0]):
        c=classifier(y_train,x_test[i],x_train)
        if(c==y_test[i]):
            score+=1
    return (score/x_test.shape[0])

#### 

In [15]:
print(score(y_train,x_test,x_train))

0.940923076923077
